allowBuilds:
  edgedriver: false
  esbuild: true
  geckodriver: false
  unrs-resolver: true

ignoredOptionalDependencies:
  - sharp

overrides:
  "@wdio/tauri-service@1.2.0>@wdio/native-utils": "2.5.0"
  "@blocknote/core@0.36.0>uuid": "11.1.1"
  "@babel/core": "7.29.1"
  markdown-it: "14.3.0"
  postcss: "8.5.14"
  prosemirror-model: "1.25.3"
  prosemirror-state: "1.4.3"
  prosemirror-tables: "1.8.1"
  prosemirror-transform: "1.10.4"
  prosemirror-view: "1.41.3"

patchedDependencies:
  '@wdio/tauri-service@1.2.0': patches/@wdio__tauri-service@1.2.0.patch
